spring:
  application:
    name: vnc-proxy
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

vnc:
  servers: >
   127.0.0.1:5900,
   192.168.50.25:5900,
   192.168.50.28:5900